name: tests
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.3
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Install libgit2
      run: |
        git clone https://github.com/libgit2/libgit2.git ~/libgit2
        cd ~/libgit2
        git checkout v1.0.1
        mkdir build && cd build
        sudo cmake .. -DCMAKE_INSTALL_PREFIX=$PKG_CONFIG_PATH/libgit2
        sudo cmake --build . --target install

    - name: Vet
      run: make vet
    
    - name: Test
      run: make test-cover
    
    - name: Upload coverage
      uses: codecov/codecov-action@v1

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26
          args: --build-tags sqlite_vtable,static,system_libgit2
